/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenerationRequest = IDL.Record({
  'drawingBase64' : IDL.Text,
  'prompt' : IDL.Text,
});
export const GenerationId = IDL.Nat;
export const GenerationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Text,
});
export const Generation = IDL.Record({
  'id' : GenerationId,
  'status' : GenerationStatus,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'prompt' : IDL.Text,
});
export const GenerationResult = IDL.Variant({
  'ok' : Generation,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateDesign' : IDL.Func([GenerationRequest], [GenerationResult], []),
  'getRecentGenerations' : IDL.Func([], [IDL.Vec(Generation)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenerationRequest = IDL.Record({
    'drawingBase64' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const GenerationId = IDL.Nat;
  const GenerationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Text,
  });
  const Generation = IDL.Record({
    'id' : GenerationId,
    'status' : GenerationStatus,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const GenerationResult = IDL.Variant({ 'ok' : Generation, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateDesign' : IDL.Func([GenerationRequest], [GenerationResult], []),
    'getRecentGenerations' : IDL.Func([], [IDL.Vec(Generation)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };